image: ubuntu:latest

before_script:
  - echo "Install dependencies"
  - apt update -y
  - apt install -y shunit2 bashcov
  - ln -s -f $(which shunit2) /usr/local/bin/shunit2

test:
  stage: test
  script:
    - echo "Perform tests and coverage"
    - bashcov -s git-cc-test
