image: ubuntu:latest

before_script:
  - echo "Install shUnit2"
  - apt update -y
  - apt install -y shunit2
  - ln -s -f $(which shunit2) /usr/local/bin/shunit2

test:
  stage: test
  script:
    - echo "Perform tests"
    - bash git-cc-test
