#!/usr/bin/env bash

msg_type="chore"
msg_subject=""
msg_scope=""
msg_body=""
msg_breaking=""

while [ "${#}" -ge 1 ]; do
  case "$1" in
    --type)
      msg_type="$2";;
    --subject)
      msg_subject="$2";;
    --scope)
      msg_scope="$2";;
    --body)
      msg_body="$2";;
    --breaking)
      msg_breaking="$2";;
  esac && shift
done

# check if subject provided
[[ -z "${msg_subject}" ]] && echo 1>&2 "error: subject must be provided" && exit 1

msg="${msg_type}$([[ -n "${msg_scope}" ]] && printf "(%s)" "${msg_scope}"): ${msg_subject}"
msg="${msg}$([[ -n "${msg_body}" ]] && printf "\n\n%s" "${msg_body}")"
msg="${msg}$([[ -n "${msg_breaking}" ]] && printf "\n\nBREAKING CHANGE: %s" "${msg_breaking}")"

echo "${msg}"
